### ISSUE TITLE
Configuration flag: restart if you haven't gotten an event

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-data#48]

**Comment by pglowacky** [comment]
@victorges  Does this relate to any ongoing product priorities? Trying to figure out the priority of some of these backlog tickets.

**Comment by victorges** [comment]
@pglowacky This is more of a reliability workaround, which was thought when we were having a lot of connectivity errors between `analyzer` and RabbitMQ. This started happening much less often in the past few weeks, since @iameli improved our nodes situation regarding disk&cpu pressure and upgraded our wireguard version and that apparently improved the RabbitMQ reliability.

I'm going to close this one for now, and we can re-evaluate if we want it in the future. But we probably don't need it right now (it was very much a workaround since inception).

**Comment by victorges** [comment]
Actually, this is still happening. We might need to implement it when we have time to kill some tech debt that affects our (stream health) reliability.
