### ISSUE TITLE
implement multi-region replication

### ISSUE THREAD

**Issue by iameli** [livepeer/livepeer-data#8]
Some thoughts around a multi-region replication mechanism.

It would be nice for the analyzer to learn about all Livepeer streams that are present in all datacenters. It would allow requests for `https://livepeer.com/data/stream/ABCDEF` to be routed to the appropriate datacenter without thinking about. 

We don't want all of the data replicated to every DC. Too much. Most of the events can remain local. Instead, we should replicate a smaller dataset, consisting of just the information necessary to know which Livepeer streams are present in which datacenters at which times. Something like:

```json5
{
  streamId: "ABC123",
  time: 1629716891183,
  // maybe?
  seqNo: "123"
}
```

At that point we should be smart enough to proxy requests from `/data/stream/492bdu7109ayuxt4/events` to the appropriate analyzer node in the correct region. We should even be able to handle streams moving from one datacenter to another without ending the event-stream!

**Replication mechanism**: I see two options here...

1. Subscribe directly to the RabbitMQ Stream in each other datacenter. I guess we'd need to implement authorization and expose the RabbitMQ ports publicly but that's not too bad. Good: kinda straightforward, mimics logic we already have. Bad: Every analyzer node will need to keep open `O(datacenters)` connections, not sure if that's a problem or not...

2. Subscribe to a feed of events from the other analyzer nodes directly, perhaps writing these events into a local RabbitMQ stream for durability. Good: would let us implement "mesh network" connections eventually, avoiding the `O(nodes^2)` number of connections that would be going on otherwise. Not sure. Bad: have to spend some time thinking about disconnects and retries and whatnot.

**Comment by victorges** [comment]
Just an addendum that, on `1.` it wouldn't be a matter of only a connection being held to each of the other regions, but also the streaming of all the data that goes through that RabbitMQ when we only need 1 event per stream to know "this stream is here" (we cannot subscribe to only a sub-set of the messages within a rabbitmq stream). Unless we implement some different queue/protocol only to let the other regions know where the stream is, which might not be that bad. And if the connections issue becomes a problem, we can create a "global replicator" node just like that one from Uber's Kafka, running on each region and **pushing** the events to all the other registered regions instead (could even push just to the other replicator in the other region and avoid having to expose the RabbitMQs to the internet, which doesn't seem ideal) 

I also wondered, what about doing something like or leveraging from the multi-region routing we do for the API and/or streams playback? Say, either:
 - Creating routes in traefik for the `/data/stream/xxx/*` routes, pointing to other regions 
 - If not a Traefik rule, maybe we could use `etcd` as our single global replicated storage about where the streams are, and leverage from the existing `mirror-maker`? Long-term could even be like a CRD with multiple config "side-effects" in the infra.
 - Otherwise, merging with the authorization idea we discussed, the `auth-server` could also return some metadata about what other region (or URL) the stream is currently on and the `analyzer` proxies to that region. This would be possible **now** because this `auth-server` is the API and the API saves that in the DB (might not be the best path considering "the future" of the API?)

**Comment by iameli** [comment]
> Unless we implement a separate exchange/queue only to let the other regions know where the stream is, which might not be that bad.

Yep, this is what I was envisioning. Maybe the analyzer subscribes to both the "local state" stream and the "replicated" stream, and if any replication-pertinent streams haven't been pushed to the replication stream yet, it does so? (The logic for that is quite similar to pushing "Livepeer stream present" information to regions that don't yet have them, come to think of it...)

> And if the connections issue becomes a problem, we can create a "global replicator" node just like that one from Uber's Kafka, running on each region and **pushing** the events to all the other registered regions instead. It could even push to rabbit only through to the other replicator in the other region, and avoid having to expose the RabbitMQs to the internet, which doesn't seem ideal. 

Yep, that sounds excellent. We should probably just do that.

> Creating routes in traefik for the `/data/stream/xxx/*` routes, pointing to other regions (not sure if that's what we do for playback tho, how does `mirror-maker` copy the routes to the other regions?)

Elegant, but I like the idea of being able to subscribe to an event feed that survives the rupture between a stream moving between regions. Even more tricky, it'd be nice if it could survive moving from our _local_ region to another region.

> If not a Traefik rule, maybe we could just use `etcd` as our single global replicated storage about where the streams are, and leverage from the existing `mirror-maker`? Long-term could even be like a CRD with multiple config "side-effects" in the infra (like the routes above).

My medium-term thinking right now is we want to move away from `etcd` entirely in favor of this RabbitMQ-Stream backed mechanism. We have very little introspection into etcd's performance and the mirror-maker mechanism we're using, while presently effective, is almost completely opaque. Someday soon I'll be opening a ticket to have us [implement a Traefik web backend](https://doc.traefik.io/traefik/providers/http/) on the Analyzer, but global replication is obviously a prerequisite there.

> Otherwise, merging with the authorization idea we discussed, the `auth-server` could also return some metadata about what other region (or URL) the stream is currently on and the `analyzer` proxies to that region. This would be possible **now** because this `auth-server` is the API and the API can access the current region in the DB, but it might not be the best path considering "the future" of the API I guess.

The "region" field in the Postgres database makes me nervous — are we confident it's going to always be correct in a scenario where a stream jumps back and forth between a couple of regions? If the HTTP requests or the DB modifications happen in the wrong order, it could become out-of-date. The analyzer is resilient to that kind of thing; even if the "region changed" events get added in the wrong order, we'll eventually reconcile everything and route to the correct region.

Trying this rule of thumb... anything about stream _definitions_, like profiles and RTMP push targets, lives in the API server in the Postgres database. Anything about stream _status_, like the current region, should be part of this project.

**Comment by darkdarkdragon** [comment]
>  are we confident it's going to always be correct in a scenario where a stream jumps back and forth between a couple of regions?

Just for information, mapic will not approve RTMP stream until DB is updated.
That said, we still not handle correctly case when user streams two RTMP streams `simultaneously using single stream key directly into two different regions.

Also, we shouldn't forget case of streams for which either transcoding hasn't started for some reason or was explicitly turned off (we want to support streams without transcoding in the future). For such streams there will be no events from broadcaster.
